name: Build and deploy Node.js app to Azure Web App - memoria-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      # Create a zip file with the application files
      - name: Create zip file
        uses: actions/create-zip-file@v1
        with:
          files: '.'
          dest: 'node-app.zip'

      # Upload the zip file as an artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download the zip file from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app.zip
      
      # Extract the zip file to get the application files
      - name: Extract zip file
        uses: montudor/action-zip@v0.1.0
        with:
          args: unzip -qq node-app.zip -d ./

      # Deploy the application files to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'memoria-webapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_64C6232802FE445E8F96A3E6B45B12DF }}
          package: .
